setwd("D://COURSERA//DATA_SCIENCE//4.Exploratory_Data_Analysis/Project and Assignments")
completedata <- read.table("household_power_consumption.txt", sep = ";", header=TRUE, colClasses=c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"),na.strings="?")
mydata <- subset(completedata,Date == "1/2/2007" | Date == "2/2/2007")
tmpdatetime <- paste(mydata[,1],mydata[,2])
datetime <- strptime(tmpdatetime,tz="",format="%d/%m/%Y %H:%M:%S")
png("plot3.png",height=480,width=480)
plot(datetime,mydata$Sub_metering_1,xlab="", ylab="Energy sub metering",type="l")
points(datetime,mydata$Sub_metering_2, type="l", col="red")
points(datetime,mydata$Sub_metering_3, type="l", col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1))
dev.off()
